name = "numerus"
type = "javascript"

account_id = "e91f5bec27ce334e3aa4d8fe0caa4353"
workers_dev = true
compatibility_date = "2025-03-17"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
main = "src/main.tsx"  # Specify the path to your entry-point script

[env.production]
route = "your-domain.com/*"
zone_id = "your-zone-id"